import type { NetworkAlert, NetworkEdge, NetworkNode } from '../types';

export const initialNodes: NetworkNode[] = [
  // Core Tier
  {
    id: 'gw-01',
    label: 'Internet Gateway',
    type: 'router',
    status: 'online',
    ip: '192.168.100.1',
    mac: '00:1A:2B:3C:4D:01',
    cpu: 12,
    ram: 25,
    temp: 38,
    traffic: 450,
  },
  {
    id: 'fw-01',
    label: 'Main Firewall',
    type: 'firewall',
    status: 'online',
    ip: '192.168.100.2',
    mac: '00:1A:2B:3C:4D:02',
    cpu: 18,
    ram: 42,
    temp: 41,
    traffic: 448,
  },
  {
    id: 'cr-01',
    label: 'Core Router',
    type: 'router',
    status: 'online',
    ip: '10.0.0.1',
    mac: '00:1A:2B:3C:4D:03',
    cpu: 22,
    ram: 31,
    temp: 45,
    traffic: 890,
  },

  // Distribution Tier
  {
    id: 'ds-01',
    label: 'Dist Switch A',
    type: 'switch',
    status: 'online',
    ip: '10.0.1.1',
    mac: '00:1A:2B:3C:4D:04',
    cpu: 8,
    ram: 19,
    temp: 34,
    traffic: 410,
  },
  {
    id: 'ds-02',
    label: 'Dist Switch B',
    type: 'switch',
    status: 'online',
    ip: '10.0.1.2',
    mac: '00:1A:2B:3C:4D:05',
    cpu: 6,
    ram: 17,
    temp: 32,
    traffic: 380,
  },

  // Access Tier
  {
    id: 'as-01',
    label: 'Office Switch 1',
    type: 'switch',
    status: 'online',
    ip: '10.0.2.1',
    mac: '00:1A:2B:3C:4D:06',
    cpu: 5,
    ram: 14,
    temp: 30,
    traffic: 85,
  },
  {
    id: 'as-02',
    label: 'Office Switch 2',
    type: 'switch',
    status: 'online',
    ip: '10.0.2.2',
    mac: '00:1A:2B:3C:4D:07',
    cpu: 4,
    ram: 12,
    temp: 29,
    traffic: 60,
  },
  {
    id: 'as-03',
    label: 'Server Switch',
    type: 'switch',
    status: 'online',
    ip: '10.0.3.1',
    mac: '00:1A:2B:3C:4D:08',
    cpu: 15,
    ram: 28,
    temp: 37,
    traffic: 620,
  },

  // Server Tier (connected to Server Switch as-03)
  {
    id: 'srv-web-01',
    label: 'Web Server',
    type: 'server',
    status: 'online',
    ip: '10.0.3.10',
    mac: '00:1A:2B:3C:4D:09',
    cpu: 34,
    ram: 58,
    temp: 48,
    traffic: 220,
  },
  {
    id: 'srv-db-01',
    label: 'Database Master',
    type: 'server',
    status: 'online',
    ip: '10.0.3.20',
    mac: '00:1A:2B:3C:4D:10',
    cpu: 45,
    ram: 72,
    temp: 52,
    traffic: 150,
  },
  {
    id: 'srv-mail-01',
    label: 'Exchange Mail',
    type: 'server',
    status: 'online',
    ip: '10.0.3.30',
    mac: '00:1A:2B:3C:4D:11',
    cpu: 25,
    ram: 48,
    temp: 44,
    traffic: 80,
  },
  {
    id: 'srv-nas-01',
    label: 'NAS Storage',
    type: 'server',
    status: 'online',
    ip: '10.0.3.40',
    mac: '00:1A:2B:3C:4D:12',
    cpu: 15,
    ram: 30,
    temp: 39,
    traffic: 170,
  },

  // Client Tier (connected to Access Switches as-01 and as-02)
  {
    id: 'pc-dev-01',
    label: 'Dev Workstation',
    type: 'client',
    status: 'online',
    ip: '10.0.2.50',
    mac: '00:1A:2B:3C:4D:13',
    cpu: 8,
    ram: 22,
    temp: 33,
    traffic: 15,
  },
  {
    id: 'pc-dev-02',
    label: 'Dev Laptop',
    type: 'client',
    status: 'online',
    ip: '10.0.2.51',
    mac: '00:1A:2B:3C:4D:14',
    cpu: 5,
    ram: 18,
    temp: 31,
    traffic: 10,
  },
  {
    id: 'pc-fin-01',
    label: 'Finance Desktop',
    type: 'client',
    status: 'online',
    ip: '10.0.2.60',
    mac: '00:1A:2B:3C:4D:15',
    cpu: 3,
    ram: 12,
    temp: 28,
    traffic: 5,
  },
  {
    id: 'pc-hr-01',
    label: 'HR Desktop',
    type: 'client',
    status: 'online',
    ip: '10.0.2.70',
    mac: '00:1A:2B:3C:4D:16',
    cpu: 2,
    ram: 10,
    temp: 27,
    traffic: 2,
  },
  {
    id: 'ap-01',
    label: 'Office WiFi AP',
    type: 'client',
    status: 'online',
    ip: '10.0.2.100',
    mac: '00:1A:2B:3C:4D:17',
    cpu: 12,
    ram: 35,
    temp: 36,
    traffic: 58,
  },
];

export const initialEdges: NetworkEdge[] = [
  // Core connections
  {
    id: 'e-gw-fw',
    source: 'gw-01',
    target: 'fw-01',
    bandwidth: 10,
    currentUsage: 450,
    latency: 1,
    status: 'active',
  },
  {
    id: 'e-fw-cr',
    source: 'fw-01',
    target: 'cr-01',
    bandwidth: 10,
    currentUsage: 448,
    latency: 1,
    status: 'active',
  },

  // Core to Distribution
  {
    id: 'e-cr-ds1',
    source: 'cr-01',
    target: 'ds-01',
    bandwidth: 10,
    currentUsage: 410,
    latency: 2,
    status: 'active',
  },
  {
    id: 'e-cr-ds2',
    source: 'cr-01',
    target: 'ds-02',
    bandwidth: 10,
    currentUsage: 380,
    latency: 2,
    status: 'active',
  },

  // Distribution redundancy
  {
    id: 'e-ds1-ds2',
    source: 'ds-01',
    target: 'ds-02',
    bandwidth: 20,
    currentUsage: 50,
    latency: 1,
    status: 'active',
  },

  // Distribution to Access Switches
  {
    id: 'e-ds1-as1',
    source: 'ds-01',
    target: 'as-01',
    bandwidth: 1,
    currentUsage: 85,
    latency: 3,
    status: 'active',
  },
  {
    id: 'e-ds2-as1',
    source: 'ds-02',
    target: 'as-01',
    bandwidth: 1,
    currentUsage: 0,
    latency: 3,
    status: 'inactive',
  }, // Redundant/standby
  {
    id: 'e-ds1-as2',
    source: 'ds-01',
    target: 'as-02',
    bandwidth: 1,
    currentUsage: 0,
    latency: 3,
    status: 'inactive',
  }, // Redundant/standby
  {
    id: 'e-ds2-as2',
    source: 'ds-02',
    target: 'as-02',
    bandwidth: 1,
    currentUsage: 60,
    latency: 3,
    status: 'active',
  },
  {
    id: 'e-ds1-as3',
    source: 'ds-01',
    target: 'as-03',
    bandwidth: 10,
    currentUsage: 620,
    latency: 1,
    status: 'active',
  },

  // Access Switch to Servers
  {
    id: 'e-as3-web',
    source: 'as-03',
    target: 'srv-web-01',
    bandwidth: 1,
    currentUsage: 220,
    latency: 1,
    status: 'active',
  },
  {
    id: 'e-as3-db',
    source: 'as-03',
    target: 'srv-db-01',
    bandwidth: 1,
    currentUsage: 150,
    latency: 1,
    status: 'active',
  },
  {
    id: 'e-as3-mail',
    source: 'as-03',
    target: 'srv-mail-01',
    bandwidth: 1,
    currentUsage: 80,
    latency: 2,
    status: 'active',
  },
  {
    id: 'e-as3-nas',
    source: 'as-03',
    target: 'srv-nas-01',
    bandwidth: 10,
    currentUsage: 170,
    latency: 1,
    status: 'active',
  },

  // Access Switch to Clients
  {
    id: 'e-as1-dev1',
    source: 'as-01',
    target: 'pc-dev-01',
    bandwidth: 1,
    currentUsage: 15,
    latency: 4,
    status: 'active',
  },
  {
    id: 'e-as1-dev2',
    source: 'as-01',
    target: 'pc-dev-02',
    bandwidth: 1,
    currentUsage: 10,
    latency: 5,
    status: 'active',
  },
  {
    id: 'e-as2-fin',
    source: 'as-02',
    target: 'pc-fin-01',
    bandwidth: 1,
    currentUsage: 5,
    latency: 4,
    status: 'active',
  },
  {
    id: 'e-as2-hr',
    source: 'as-02',
    target: 'pc-hr-01',
    bandwidth: 1,
    currentUsage: 2,
    latency: 4,
    status: 'active',
  },
  {
    id: 'e-as2-ap',
    source: 'as-02',
    target: 'ap-01',
    bandwidth: 1,
    currentUsage: 58,
    latency: 6,
    status: 'active',
  },
];

export const initialAlerts: NetworkAlert[] = [
  {
    id: 'a-init-1',
    timestamp: new Date(Date.now() - 60000 * 10).toISOString(),
    nodeId: 'srv-db-01',
    nodeLabel: 'Database Master',
    severity: 'warning',
    message: 'Свободное место на диске DB Master снизилось до 12%',
    acknowledged: false,
  },
];
